### ISSUE TITLE
audio book dont stores track after track no 200

### ISSUE THREAD

**Issue by marco-117** [marco-117/TonUINO#14]
[Request](https://discourse.voss.earth/t/marcos-affenbox-fork/5710/474?u=marco-117)

**Comment by marco-117** [comment]
tested, no issues found

**Comment by eloo** [comment]
i can confirm.. i have reflashed my device and the issue seems to be gone. 

maybe it was already fixed or some issues while flashing 

thanks

**Comment by marco-117** [comment]
Thank you for the confirmation

**Comment by eloo** [comment]
@marco-117 the bug happend again on my device.
this time around track no. 218

exactly the same behaviour  as mentioned in the forum.
playback stopped at track change.. 
when i replaced the card on the tonuino it is starting from the beginning.

Maybe some issue with storing the next track on the rfid card?
card is in audiobook mode

any ideas?

**Comment by eloo** [comment]
@marco-117 
here is a debug log which seems to show the error

```
track 216
set stby timer
milis 254055
disable stby timer
nxt track
write mem
on card
write Card
Auth again w. key A
write data 4...
 13  37  B3  47 02 06 05 00 00  D9 00 00 00 00 00 00 


track 217
set stby timer
milis 255236
disable stby timer
nxt track
write mem
on card
write Card
Auth again w. key A
write data 4...
 13  37  B3  47 02 06 05 00 00 01 00 00 00 00 00 00 
```

i guess the write of 01 here is wrong
this should be DA and not 01

any idea where this bug comes from?

**Comment by eloo** [comment]
@marco-117 
good news

i've found the bug or at least a workaround

the cause for the abort seems to be that the `mp3.getFolderTrackCount(myFolder->folder);` return the wrong number 
in my case it returns 217 and not 255.

so i have simply added the same call again in the audiobook case block which seems to fix the error.
here is a debug log with some debugging info from my side and the workaround implemented:

```
new tag
217
Audio Book
disable stby timer
217 mp3 in folder 6
play mp3 4
nxt track
current track
4
tracks in folder
255
write mem
on card
write Card
```
as we can see is that the new tag appears.. and a file count of 217 is read.
then i've pressed the next button and the value is read again and then returns the correct value. 

maybe its some kind of early initialization error or some timing issues.

what do you think? should we simply included that workaround here?
